name: common_test
description: Test

publish_to: "none"

version: 1.0.0+100

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  charts_flutter: ^0.12.0
  rxdart: ^0.27.3
  dio: ^4.0.4
  freezed_annotation: ^1.1.0
  retrofit: ">=3.0.0 <4.0.0"
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  go_router: ^3.0.4
  get_it: ^7.2.0
  injectable: ^1.5.3
  bloc_concurrency: ^0.2.0
  retry: ^3.1.0
  curl_logger_dio_interceptor: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.8.2
  flutter_lints: ^1.0.4
  build_runner: ^2.1.8
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.2.0
  args: ^2.1.1
  freezed: ^1.1.1
  retrofit_generator: ^4.0.1
  json_serializable: ^6.1.5
  injectable_generator: ^1.5.3
  mockito: ^5.1.0
  page_object: ^0.2.0

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
  main_locale: en
