// Mocks generated by Mockito 5.1.0 from annotations
// in common_test/test/widget/location_list_screen_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:common_test/domain/model/location_resolution.dart' as _i2;
import 'package:common_test/domain/repository/location_repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeLocationResolution_0 extends _i1.Fake
    implements _i2.LocationResolution {}

/// A class which mocks [LocationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationRepository extends _i1.Mock
    implements _i3.LocationRepository {
  MockLocationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.LocationResolution> getLocationList() => (super.noSuchMethod(
          Invocation.method(#getLocationList, []),
          returnValue:
              Future<_i2.LocationResolution>.value(_FakeLocationResolution_0()))
      as _i4.Future<_i2.LocationResolution>);
}
